Style/RedundantSelf:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'app/controllers/users/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile*'
    - 'Rakefile'