language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake spec
test:
  adapter: postgresql
  database: travis_ci_test
