language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
test:
  adapter: postgresql
  database: travis_ci_test
