# toolbar:
  # - styleselect | bold italic | undo redo | format | table
  # - colorpicker backcolor forecolor | emoticons
  # - image media | link | hr | spellchecker
menubar: false
plugins:
  - link
  - textcolor
  - colorpicker
  - hr
  - spellchecker
  - wordcount
  - uploadimage
toolbar: 'undo redo |  formatselect | bold italic backcolor forecolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | link hr uploadimage'
min_height: 500